### ISSUE TITLE
got error after executing the scrape.sh file.

### ISSUE THREAD

**Issue by shadmanhere** [voscarmv/ycombinator_githubs#4]
After running the scrape.sh everything works fine until we reach jsonize.sh.
I got this error 
`./jsonize.sh: 3: Syntax error: redirection unexpected`
I didn't get this error when I manually executed the same command, 
```
cat 05_final_repos.csv | \
    ./jsonize.sh | \
    tac | \
    sed '2s/,//' | \
    tac > 06_repos.json
```

The OS I used is ubuntu on wsl.

**Comment by voscarmv** [comment]
@shadmanhere please run it on gitpod

**Comment by voscarmv** [comment]
Also, please run some unit tests on the change you made to jsonize.sh before running the script and uploading the main list used by issue-finder
